### ISSUE TITLE
避免在model 中使用UrlHelper

### ISSUE THREAD

**Issue by ronail** [wu790616/xplorer#96]
在Bookmark#notify，Comment#notify，Like#notify，Reply#notify 和 UserFollowship#notify 中都有使用`Rails.application.routes.url_helpers.issue_path` 這個method，但UrlHelper設計上是用來在View 中用來動態產生連結的，一般不會用來儲存在database

建議做法是先在NotificationsHelper建一個notifable_link(notification) method 以Notification#notifiable的class 判斷，產生相對的url，再在 `notifications/_share_list.html.erb` 中呼叫這個helper method來使用

**Comment by wu790616** [comment]
將url_helpers移至NotificationsHelper，並在_share_list.html.erb中呼叫method產生連結，
移除model中的url_helper
