### ISSUE TITLE
[Product Feedback] 查看留言應該優先於回覆留言

### ISSUE THREAD

**Issue by dlackty** [wu790616/xplorer#99]
如下圖，當使用者遇到巢狀留言時，會先看到留言表單、才會看到巢狀內容，有點不符合使用情境。
<img width="1090" alt="xplorer" src="https://user-images.githubusercontent.com/14349/46597066-2b87c200-cb11-11e8-8df9-5b40df7edf93.png">

**Comment by miki770420** [comment]
https://github.com/wu790616/xplorer/pull/101
根據評審建議，微調留言區格式。
